name: meetbot_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animated_text_kit: ^4.2.2    
  flutter_spinkit: ^5.1.0

  async: ^2.11.0
  
  flutter_secure_storage: ^9.2.2

  google_mobile_ads: ^5.1.0   #ads

  url_launcher: ^6.3.0


  #app ui
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

  # app_settings: ^5.1.1
  flutter_i18n: ^0.36.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/elements/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "assets/elements/foreground.png"
  adaptive_icon_foreground: "assets/elements/icon.png"



flutter_native_splash:
  android_gravity: clip_vertical
  color: "#1B1B1B"
  image: assets/elements/icon12.png
  color_dark: "#1B1B1B"
  image_dark: assets/elements/icon12.png
  ios_content_mode: scaleAspectFill
 
flutter:
  assets:
    - assets/  
    - assets/json/
  
  fonts:
    - family: weekend
      fonts:
        - asset: assets/fonts/the_weekend.otf
          weight: 900
          
    - family: zametka
      fonts:
        - asset: assets/fonts/zametka.otf

uses-material-design: true